"""add job dependencies and blocked status

Revision ID: 3d5fb332397d
Revises: fd9ffafec0e7
Create Date: 2026-08-22 11:40:17.508581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5fb332397d'
down_revision: Union[str, None] = 'fd9ffafec0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate does NOT detect new members added to an existing
    # Postgres native ENUM type — it only diffs table/column structure.
    # Caught by cross-checking the model's JobStatus enum against what
    # autogenerate actually produced: BLOCKED was silently missing here.
    op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'BLOCKED'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('depends_on_job_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_jobs_depends_on_job_id'), 'jobs', ['depends_on_job_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'jobs', ['depends_on_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_depends_on_job_id'), table_name='jobs')
    op.drop_column('jobs', 'depends_on_job_id')
    # ### end Alembic commands ###

    # Postgres has no ALTER TYPE ... DROP VALUE — removing an enum member
    # requires recreating the type (and every column/index using it),
    # which risks data loss if any row still has status='blocked'. Rather
    # than pretend to support it, this is a documented, deliberate no-op:
    # downgrading past this migration leaves 'blocked' as a valid (unused)
    # jobstatus value. That's a real Postgres limitation, not an oversight.
