"""initial schema

Revision ID: fd9ffafec0e7
Revises: 
Create Date: 2026-08-22 07:39:48.177196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd9ffafec0e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('celery_worker_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='workerstatus'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('worker_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('active_jobs_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_heartbeats_worker_id'), 'worker_heartbeats', ['worker_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('org_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_project_name_per_org')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_queue_name_per_project')
    )
    op.create_index(op.f('ix_queues_project_id'), 'queues', ['project_id'], unique=False)
    op.create_table('job_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('queue_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=120), nullable=False),
    sa.Column('payload_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_schedules_queue_id'), 'job_schedules', ['queue_id'], unique=False)
    op.create_table('retry_policies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('queue_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('strategy', sa.Enum('FIXED', 'LINEAR', 'EXPONENTIAL', name='retrystrategy'), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('base_delay_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retry_policies_queue_id'), 'retry_policies', ['queue_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('queue_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('schedule_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('retry_policy_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCHEDULED', 'CLAIMED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTER', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('current_retry_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=155), nullable=True),
    sa.Column('claimed_by_worker_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_policy_id'], ['retry_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['job_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queue_id', 'idempotency_key', name='uq_job_idempotency_per_queue')
    )
    op.create_index(op.f('ix_jobs_batch_id'), 'jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_jobs_celery_task_id'), 'jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_jobs_queue_id'), 'jobs', ['queue_id'], unique=False)
    op.create_index('ix_jobs_queue_status', 'jobs', ['queue_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('dead_letter_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('original_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count_at_failure', sa.Integer(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_jobs_job_id'), 'dead_letter_jobs', ['job_id'], unique=True)
    op.create_table('job_executions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('worker_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCHEDULED', 'CLAIMED', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTER', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_executions_job_id'), 'job_executions', ['job_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_execution_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', name='loglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_execution_id'], ['job_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_job_execution_id'), 'job_logs', ['job_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_logs_job_execution_id'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_job_executions_job_id'), table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index(op.f('ix_dead_letter_jobs_job_id'), table_name='dead_letter_jobs')
    op.drop_table('dead_letter_jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('ix_jobs_queue_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_queue_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_celery_task_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_batch_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_retry_policies_queue_id'), table_name='retry_policies')
    op.drop_table('retry_policies')
    op.drop_index(op.f('ix_job_schedules_queue_id'), table_name='job_schedules')
    op.drop_table('job_schedules')
    op.drop_index(op.f('ix_queues_project_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_worker_heartbeats_worker_id'), table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_table('organizations')
    op.drop_table('workers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Autogenerate does NOT emit these: Postgres native ENUM types are
    # created as a side effect of the first column that uses them, but
    # dropping the table that used them does not drop the type itself.
    # Without this, upgrade -> downgrade -> upgrade fails on the second
    # upgrade with "type already exists" — caught by testing the round
    # trip, not by inspection.
    sa.Enum(name='workerstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='jobstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='retrystrategy').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='loglevel').drop(op.get_bind(), checkfirst=True)
